### ISSUE TITLE
Milestone: Menu Upload

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-menu-data#1]
There are a number of tasks that need to be completed to get the digitized menu data.

- [ ] Add a nice README to the project as an overview of the data. ~ 2hr qh
- [x] Get the folder metadata from special Collections.  Act3 sez they were given that.
- [x] Get a list of all the menu front pages, so we can determine where each catalog starts and stops.  According to Act3, this was not necessarily the same as the individual folder data.
- [ ] Determine the extent that we will add new metadata #3 ~ 40hr nw, ~16hr qj
- [ ] Create a script that creates the cropped and leveled full, 2x and thumbnails for each page #2 ~10hrs qh
- [ ] Go through by hand and create the proper aspect ratio (match catalogs) for the menus.  These can be subsets of the data. ~ 8hr hs
- [ ] Run the images through tesseract in order to create the OCR required for text searching. ~ 16hr qh/jm
- [ ] Create a Makefile script that uploads that data into wine-api.   ~ 16 hr qh/jm
- [ ] Dump and Save that file as the data for the catalog tool. ~ 16 qh 

Probably not part of this milestone, but to thiink about:

- [ ] See if we can make a similar version in Fedora ~ 40hr  qh/jm

## Estimated Times.

84 qh
32 jm
8 kh
